### PR TITLE
Add symfony 4 as a viable version and run composer update.

### PR DESCRIPTION
**Pull request by lars-kaustik**
Signed-off-by: Lars Brodén <lars.broden@allevi.se>

### CODE REVIEW

**Comment by lars-kaustik** [comment]
Out of all the three tests one is failing - not sure why:
image

**Comment by christiansipola** [comment]
i will have a look...

**Comment by christiansipola** [comment]
I changed the command in https://github.com/Kaustik/github-tools/commit/062e3a77fe2713ecffaff2603bd65b2a884f8ef7#diff-a16fbbae1b8b4f055949cfe244cf3952d225f1329d8c29f4b553207f8626da6b without updating the test :(

**Comment by christiansipola** [comment]
so just update to test

**Comment by lars-kaustik** [comment]
@christiansipola Updated.

**Review by christiansipola — APPROVED** [review]

**Pull request merged**
